#!/usr/bin/env bash
# digest.sh — assemble the operator digest (BM-DIGEST-01) from what can be READ, not remembered.
#
# orchestrate-build writes an operator digest at every pause, at session end, at every usage-limit event,
# and at the cadence the ledger's OPERATING MODE names (e.g. once per wave). This script gathers the
# mechanical part — the harness, the ledger state, the validator, the CI of every open chain PR, the merges
# since the last digest (read from GitHub, whoever made them), the default branch, the owed human work —
# and takes the session's own lines as flags (production anomalies read, spend, agent usage). It never
# invents a figure: a line it cannot read says so ("unknown (gh absent)", "not reported").
#
# Usage:
#   digest.sh --ledger <docs/build/LEDGER.md> [--trigger <pause|wave|round|session-end|usage-limit|block|gate>]
#             [--production "<what was read, and what was found>"] [--spend "<infra spend + source>"]
#             [--usage "<runs; usage per run (median, max); cumulative; projection; usage-limit events>"]
#             [--exposed yes|no] [--since ISO] [--write] [--worktree DIR] [--max-prs N] [--now ISO] [--json PATH]
#
#   --write     append the digest to <memoryRoot>/reports/digests/<date -u +%F>.md (append-only; created
#               with a title line when new). Without it the digest is only printed.
#   --since     list merges since this time (default: the newest earlier digest's timestamp).
#   --exposed   yes = a secret value appeared in a transcript: the digest records `exposed: yes` and the
#               script exits 3 — stop for rotation (the value itself is never written).
#
# Exit codes: 0 digest printed (and written) · 3 stop: a secret-shaped token in the digest (nothing written)
#   or --exposed yes · 5 the ledger is unreadable · 1 usage.
# Bash 3.2+, git; gh for the GitHub reads (absent → those lines read `unknown`). Read-only except --write.

set -uo pipefail
LEDGER="" ; TRIGGER="pause" ; PROD="" ; SPEND="" ; USAGE="" ; EXPOSED="no" ; SINCE="" ; WRITE=0 ; WT="" ; MAXPR=60 ; NOW="" ; JSON=""
while [ $# -gt 0 ]; do
  case "$1" in
    --ledger) LEDGER="${2:-}"; shift 2 ;;
    --trigger) TRIGGER="${2:-}"; shift 2 ;;
    --production) PROD="${2:-}"; shift 2 ;;
    --spend) SPEND="${2:-}"; shift 2 ;;
    --usage) USAGE="${2:-}"; shift 2 ;;
    --exposed) EXPOSED="${2:-no}"; shift 2 ;;
    --since) SINCE="${2:-}"; shift 2 ;;
    --write) WRITE=1; shift ;;
    --worktree) WT="${2:-}"; shift 2 ;;
    --max-prs) MAXPR="${2:-60}"; shift 2 ;;
    --now) NOW="${2:-}"; shift 2 ;;
    --json) JSON="${2:-}"; shift 2 ;;
    -h|--help) awk 'NR > 1 && !/^#/ {exit} NR > 1 {sub(/^# ?/, ""); print}' "$0"; exit 0 ;;
    *) echo "digest.sh: unknown arg: $1 (try --help)" >&2; exit 1 ;;
  esac
done
[ -n "$LEDGER" ] && [ -f "$LEDGER" ] || { echo "digest.sh: --ledger <existing LEDGER.md> required" >&2; exit 5; }
LEDGER="$(cd "$(dirname "$LEDGER")" && pwd)/$(basename "$LEDGER")"
ROOT="$(dirname "$LEDGER")"                       # the memory root (docs/build)
REPO="$(git -C "$ROOT" rev-parse --show-toplevel 2>/dev/null || dirname "$(dirname "$ROOT")")"
[ -n "$WT" ] || WT="$REPO"
SELF="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CIB="$SELF/ci-boundary.sh"; VAL="$SELF/../../build-memory/scripts/check-build-memory.sh"
NOW="${NOW:-$(date -u +%Y-%m-%dT%H:%M:%SZ)}"; DAY="$(printf '%s' "$NOW" | cut -c1-10)"
TMP="$(mktemp -d)"; trap 'rm -rf "$TMP" 2>/dev/null' EXIT

val() { grep -m1 -E "^[[:space:]]*${1}:" "$LEDGER" 2>/dev/null | sed -E "s/^[[:space:]]*${1}:[[:space:]]*//; s/[[:space:]]*#.*$//; s/[[:space:]]*$//" | cut -c1-160; }
HAVE_GH=0; command -v gh >/dev/null 2>&1 && HAVE_GH=1
DIGDIR="$ROOT/reports/digests"
if [ -z "$SINCE" ] && [ -d "$DIGDIR" ]; then
  SINCE="$(cat "$DIGDIR"/*.md 2>/dev/null | grep -oE '^## [0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9:]{8}Z' | sed 's/^## //' | sort | tail -1)"
fi

# BUILD_INDEX: PR number → ticket (the chain's PRs)
: > "$TMP/prs"
if [ -f "$ROOT/BUILD_INDEX.md" ]; then
  LC_ALL=C awk -F'|' '
    function t(x) { gsub(/[*`]/, "", x); gsub(/^[[:space:]]+|[[:space:]]+$/, "", x); return x }
    /^\|/ { if ($0 ~ /^\|[-|: ]+\|[[:space:]]*$/) next
            a = b = 0; for (i = 1; i <= NF; i++) { c = tolower(t($i)); if (c == "ticket") a = i; if (c == "pr") b = i }
            if (a && b) { tc = a; pc = b; next }
            if (tc && pc && match($pc, /#[0-9]+/)) { tk = t($tc); sub(/[[:space:]].*$/, "", tk); print substr($pc, RSTART + 1, RLENGTH - 1) "\t" tk } }' "$ROOT/BUILD_INDEX.md" | sort -u -k1,1n > "$TMP/prs"
fi

{
  echo "## $NOW — operator digest ($TRIGGER)"
  echo "<!-- digest/1 · generated by orchestrate-build digest.sh; the Production, Spend and Usage lines are the session's own report -->"
  echo
  H="$(val harness)"; echo "- **Harness:** ${H:-(not recorded in CURRENT STATE \`harness:\`)}"
  echo "- **Ledger:** projectStatus $(val projectStatus) · nextTicket $(val nextTicket) · lastCompleted $(val lastCompleted) · blockedOn $(val blockedOn) · pauseRequested $(val pauseRequested) · returnPass $(val returnPass) · round $(val round)"
  if [ -f "$VAL" ]; then
    vout="$(bash "$VAL" "$REPO" --json "$TMP/v.json" 2>&1)"; vrc=$?
    vsum="$(printf '%s\n' "$vout" | grep -E '^  (✓|✗)' | head -1 | sed -E 's/^  //')"
    echo "- **Validator:** check-build-memory.sh exit $vrc — ${vsum:-no summary}"
  else
    echo "- **Validator:** unknown (check-build-memory.sh not found)"
  fi
  # CI of every open chain PR (one read each; never "green" without a read)
  if [ "$HAVE_GH" -eq 0 ]; then
    echo "- **CI of open chain PRs:** unknown (gh absent) — never treated as green"
  else
    gh pr list --state open --limit 200 --json number,headRefName --jq '.[] | "\(.number)\t\(.headRefName)"' 2>/dev/null > "$TMP/open" || : > "$TMP/open"
    awk -F'\t' 'NR == FNR {o[$1] = 1; next} ($1 in o)' "$TMP/open" "$TMP/prs" | sort -k1,1nr | head -n "$MAXPR" > "$TMP/openchain"
    nopen="$(wc -l < "$TMP/openchain" | tr -d ' ')"; nred=0
    echo "- **CI of open chain PRs** (${nopen} open; read $NOW, one read each):"
    if [ "$nopen" -eq 0 ]; then echo "  - (no open chain PR)"; fi
    while IFS="$(printf '\t')" read -r pr tk; do
      [ -n "$pr" ] || continue
      out="$(bash "$CIB" --pr "$pr" --worktree "$WT" --no-wait 2>/dev/null)"; rc=$?; last="$(printf '%s\n' "$out" | tail -1)"
      case "$rc" in 0) st="pass" ;; 3) st="RED"; nred=$((nred + 1)) ;; 4) st="pending" ;; *) st="unknown" ;; esac
      echo "  - #$pr ($tk) — $st — $last"
    done < "$TMP/openchain"
  fi
  # merges since the last digest, by anyone (read from GitHub)
  if [ "$HAVE_GH" -eq 0 ]; then
    echo "- **Merges since ${SINCE:-the start}:** unknown (gh absent)"
  else
    search=""; [ -n "$SINCE" ] && search="merged:>=$SINCE"
    gh pr list --state merged --limit 100 ${search:+--search "$search"} --json number,title,mergedAt,mergedBy,baseRefName \
      --jq '.[] | "\(.number)\t\(.title)\t\(.mergedAt)\t\(.mergedBy.login)\t\(.baseRefName)"' 2>/dev/null > "$TMP/merged" || : > "$TMP/merged"
    echo "- **Merges since ${SINCE:-(no earlier digest)}** (read from GitHub $NOW):"
    if [ ! -s "$TMP/merged" ]; then echo "  - (none)"; fi
    while IFS="$(printf '\t')" read -r n title at by base; do
      [ -n "$n" ] || continue
      chain=""; awk -F'\t' -v n="$n" '$1 == n {f = 1} END {exit !f}' "$TMP/prs" && chain=" (chain row)"
      echo "  - #$n \"$(printf '%s' "$title" | cut -c1-80)\" → $base, merged by $by at $at$chain"
    done < "$TMP/merged"
  fi
  # the default branch and whether the chain still descends from it
  def="$(git -C "$WT" symbolic-ref -q --short refs/remotes/origin/HEAD 2>/dev/null || echo origin/main)"
  if git -C "$WT" rev-parse --verify -q "$def" >/dev/null 2>&1; then
    tip="$(val chainTip)"; desc="unknown"
    if [ -n "$tip" ] && git -C "$WT" rev-parse --verify -q "$tip" >/dev/null 2>&1; then
      git -C "$WT" merge-base --is-ancestor "$def" "$tip" 2>/dev/null && desc="yes" || desc="NO — an off-stack merge or a rebase: a blockedOn for the operator"
    fi
    echo "- **Default branch:** $def @ $(git -C "$WT" rev-parse --short "$def") ($(git -C "$WT" log -1 --format=%cI "$def")) — chain descends from it: $desc"
  else
    echo "- **Default branch:** unknown ($def not fetched)"
  fi
  # owed human and rights work: OPEN/PARTIAL kind-P deferral rows (owner, trigger)
  echo "- **Owed human and rights work** (OPEN/PARTIAL kind-P rows, DEFERRALS rule 5):"
  DEF="$REPO/docs/tickets/DEFERRALS.md"
  if [ -f "$DEF" ]; then
    LC_ALL=C awk -F'|' '
      function trim(x) { gsub(/^[[:space:]]+|[[:space:]]+$/, "", x); return x }
      /^\|[[:space:]]*id[[:space:]]*\|/ { kc = uc = ic = 0; for (i = 1; i <= NF; i++) { c = tolower(trim($i)); if (c == "kind") kc = i; if (c == "unblocked by") uc = i; if (c == "item") ic = i } next }
      /^\|[[:space:]]*D-/ && kc { k = $kc; gsub(/[[:space:]*`_]/, "", k); if (k != "P") next
        last = ""; for (i = NF; i >= 1; i--) if (trim($i) != "") { last = $i; break }
        s = toupper(last); if (s !~ /^[^A-Z]*(OPEN|PARTIAL)/) next
        u = uc ? $uc : ""; ow = "owner: ?"; tr = "trigger: ?"
        if (match(u, /owner:[^;·]*/)) ow = trim(substr(u, RSTART, RLENGTH)); if (match(u, /trigger:[^;·]*/)) tr = trim(substr(u, RSTART, RLENGTH))
        print "  - " trim($2) " — " substr(trim(ic ? $ic : ""), 1, 70) " — " ow " — " tr; n++ }
      END { if (!n) print "  - (none recorded)" }' "$DEF"
  else
    echo "  - (no DEFERRALS.md)"
  fi
  echo "- **Production anomalies read this session:** ${PROD:-not reported by the session}"
  echo "- **Spend:** infrastructure ${SPEND:-not reported by the session} · agent usage ${USAGE:-not reported by the session (\"not measured\" is a valid answer; a figure is never invented)}"
  if [ "$EXPOSED" = "yes" ]; then echo "- **Secrets:** exposed: yes — stop for rotation (the value is never written here)"
  else echo "- **Secrets:** exposed: no"; fi
  echo
} > "$TMP/digest.md"

cat "$TMP/digest.md"
SECRET_RE='AKIA[0-9A-Z]{16}|sk-[A-Za-z0-9]{20,}|ghp_[A-Za-z0-9]{36}|-----BEGIN [A-Z ]*PRIVATE KEY-----|xox[baprs]-'
if grep -qE "$SECRET_RE" "$TMP/digest.md"; then
  echo "digest.sh: STOP — a secret-shaped token is in the digest (from a PR title or a passed line); nothing written. Record exposed: yes and stop for rotation." >&2
  exit 3
fi
if [ "$WRITE" -eq 1 ]; then
  mkdir -p "$DIGDIR"; F="$DIGDIR/$DAY.md"
  [ -f "$F" ] || printf '# Operator digests — %s (append-only; BM-DIGEST-01)\n\n' "$DAY" > "$F"
  cat "$TMP/digest.md" >> "$F"
  echo "digest.sh: appended to ${F#$REPO/}"
fi
[ -n "$JSON" ] && printf '{"schema":"digest/1","at":"%s","trigger":"%s","written":%s,"exposed":"%s"}\n' "$NOW" "$TRIGGER" "$([ "$WRITE" -eq 1 ] && echo true || echo false)" "$EXPOSED" > "$JSON"
[ "$EXPOSED" = "yes" ] && { echo "digest.sh: exposed: yes — stop for rotation." >&2; exit 3; }
exit 0
