#!/usr/bin/env bash
# adr-index.sh — regenerate docs/adr/README.md from the ADR files. (BM-ADR-02.)
#
# The index is DERIVED, never hand-maintained: one row per ADR-NNN-<slug>.md, in
# numeric order, columns ADR / Title / Ticket / Status. The generated file carries
# a marker comment so the validator (check-build-memory.sh) can regenerate to a
# temp file and diff — a hand edit is a violation, not a merge.
#
# Usage:
#   adr-index.sh [adr_dir]            # writes <adr_dir>/README.md
#   adr-index.sh --check [adr_dir]    # print the index to stdout; write nothing
#
# Arguments:
#   adr_dir — the ADR directory (default: docs/adr relative to cwd).
#
# A human-authored trailing section (from the first '## ' heading to EOF — e.g. a '## Notes'
# prose block) is preserved across regeneration, so the generated table and hand-kept prose coexist.
#
# Each ADR file is parsed for:
#   - title  : the H1 `# ADR-NNN: <title>`
#   - status : the `- **Status:** <value>` header bullet
#   - ticket : the `- **Ticket:** <value>` header bullet
# Missing status/ticket render as `—`. Files are ordered by their zero-stripped
# numeric NNN; ties keep filename order.
#
# Output:
#   Default: (re)writes <adr_dir>/README.md. --check: prints to stdout only.
#
# Exit codes:
#   0 — index generated (or printed)
#   1 — adr_dir does not exist
#
# Mutating in default mode (writes README.md); read-only with --check.
# Compatible with bash 3.2+ (macOS default). No associative arrays, no mapfile.

set -o pipefail

CHECK=0
if [ "${1:-}" = "--check" ]; then CHECK=1; shift; fi
ADR_DIR="${1:-docs/adr}"

[ -d "$ADR_DIR" ] || { echo "adr-index.sh: no such directory: $ADR_DIR" >&2; exit 1; }

MARKER='<!-- generated by build-memory adr-index; do not edit -->'

# field <file> <bullet-label> — value of a `- **Label:** value` header bullet, or empty.
field() {
  grep -m1 -E "^[[:space:]]*-[[:space:]]*\*\*${2}:\*\*" "$1" 2>/dev/null \
    | sed -E "s/^[[:space:]]*-[[:space:]]*\*\*${2}:\*\*[[:space:]]*//; s/[[:space:]]*$//"
}

# Collect "NNN<TAB>filename" for numeric sort, then emit rows in that order.
tmp_rows="$(mktemp)" ; notes_tmp="$(mktemp)"
trap 'rm -f "$tmp_rows" "$notes_tmp" 2>/dev/null' EXIT

# Preserve any human-authored trailing section (from the first '## ' heading to EOF) so a
# generated index and hand-kept notes (e.g. a '## Notes' paragraph, Eleutheria's Appendix-F prose)
# can coexist and survive regeneration. The generated part below has no '## ' heading, so the
# first one in the existing file marks the boundary; regeneration normalises to one blank line
# before it. Read the existing README BEFORE the write truncates it.
if [ -f "$ADR_DIR/README.md" ]; then
  awk '/^##[[:space:]]/{f=1} f' "$ADR_DIR/README.md" > "$notes_tmp"
fi

for f in "$ADR_DIR"/ADR-*.md; do
  [ -f "$f" ] || continue
  base="$(basename "$f")"
  # NNN is the digits immediately after "ADR-".
  nnn="$(printf '%s\n' "$base" | sed -E 's/^ADR-0*([0-9]+).*$/\1/')"
  case "$nnn" in ''|*[!0-9]*) continue ;; esac   # skip non-numeric (e.g. README, _TEMPLATE)
  printf '%s\t%s\n' "$nnn" "$base" >> "$tmp_rows"
done

emit() {
  printf '%s\n' "$MARKER"
  printf '# Architecture Decision Records\n\n'
  printf 'One row per ADR, numeric order. Regenerate with `build-memory adr-index`\n'
  printf '(`scripts/adr-index.sh`); never hand-edit — the validator diffs a regeneration.\n\n'
  printf '| ADR | Title | Ticket | Status |\n'
  printf '|---|---|---|---|\n'
  if [ -s "$tmp_rows" ]; then
    sort -n -k1,1 "$tmp_rows" | while IFS="$(printf '\t')" read -r _n base; do
      f="$ADR_DIR/$base"
      title="$(grep -m1 -E '^#[[:space:]]+ADR-[0-9]+:' "$f" | sed -E 's/^#[[:space:]]+ADR-[0-9]+:[[:space:]]*//; s/[[:space:]]*$//')"
      [ -n "$title" ] || title='—'
      status="$(field "$f" Status)"; [ -n "$status" ] || status='—'
      ticket="$(field "$f" Ticket)"; [ -n "$ticket" ] || ticket='—'
      # ADR label = the file's own NNN, zero-padded to 3 as written in the H1.
      adr_id="$(grep -m1 -E '^#[[:space:]]+ADR-[0-9]+:' "$f" | sed -E 's/^#[[:space:]]+(ADR-[0-9]+):.*$/\1/')"
      [ -n "$adr_id" ] || adr_id="$(printf '%s' "$base" | sed -E 's/^(ADR-[0-9]+).*$/\1/')"
      printf '| [%s](%s) | %s | %s | %s |\n' "$adr_id" "$base" "$title" "$ticket" "$status"
    done
  fi
  # Re-append any preserved human trailing section (see the capture above).
  if [ -s "$notes_tmp" ]; then
    printf '\n'
    cat "$notes_tmp"
  fi
}

if [ "$CHECK" -eq 1 ]; then
  emit
else
  emit > "$ADR_DIR/README.md"
  echo "adr-index.sh: wrote $ADR_DIR/README.md"
fi
exit 0
