#!/usr/bin/env bash
# adr-index.sh — regenerate docs/adr/README.md from the ADR files. (BM-ADR-02.)
#
# The index is DERIVED, never hand-maintained: one row per ADR-NNN-<slug>.md, in
# numeric order, columns ADR / Title / Ticket / Status. The generated file carries
# a marker comment so the validator (check-build-memory.sh) can regenerate to a
# temp file and diff — a hand edit is a violation, not a merge.
#
# Usage:
#   adr-index.sh [adr_dir]                     # writes <adr_dir>/README.md
#   adr-index.sh --check [adr_dir]             # print the index to stdout; write nothing
#   adr-index.sh --check --legacy [adr_dir]    # print what the 0.4.0 parser produced (the
#                                              # validator uses it to recognise an index that is
#                                              # merely stale, not hand-edited)
#
# Arguments:
#   adr_dir — the ADR directory (default: docs/adr relative to cwd).
#
# A human-authored trailing section (from the first '## ' heading to EOF — e.g. a '## Notes'
# prose block) is preserved across regeneration, so the generated table and hand-kept prose coexist.
#
# Each ADR file is parsed for the header forms in use (SK-21; landed ADR bodies are frozen, so the
# generator adapts, never the ADRs):
#   - title  : the H1 `# ADR-NNN: <title>`, `# ADR-NNN — <title>` or `# ADR-NNN - <title>`
#   - ticket : the first of the header fields `Ticket`, `Phase`, `Phase / ticket`
#   - status : the header field `Status`; an appended `Superseded by ADR-MMM …` line (BM-ADR-01's
#              only permitted post-landing append) replaces it
#   A header field is `- **Label:** value`, `- Label: value`, `**Label:** value` or `Label: value`
#   (above the first `## ` heading). A `|` inside a value is escaped. Missing values render as `—`
#   (the validator warns on every `—` cell). Files are ordered by their zero-stripped numeric NNN;
#   ties keep filename order.
#
# Output:
#   Default: (re)writes <adr_dir>/README.md. --check: prints to stdout only.
#
# Exit codes:
#   0 — index generated (or printed)
#   1 — adr_dir does not exist
#
# Mutating in default mode (writes README.md); read-only with --check.
# Compatible with bash 3.2+ (macOS default). No associative arrays, no mapfile.

set -o pipefail

CHECK=0 ; LEGACY=0
while [ $# -gt 0 ]; do
  case "$1" in
    --check)  CHECK=1; shift ;;
    --legacy) LEGACY=1; shift ;;
    *) break ;;
  esac
done
ADR_DIR="${1:-docs/adr}"

[ -d "$ADR_DIR" ] || { echo "adr-index.sh: no such directory: $ADR_DIR" >&2; exit 1; }

MARKER='<!-- generated by build-memory adr-index; do not edit -->'

# legacy_field <file> <bullet-label> — the 0.4.0 reader: only `- **Label:** value`.
legacy_field() {
  grep -m1 -E "^[[:space:]]*-[[:space:]]*\*\*${2}:\*\*" "$1" 2>/dev/null \
    | sed -E "s/^[[:space:]]*-[[:space:]]*\*\*${2}:\*\*[[:space:]]*//; s/[[:space:]]*$//"
}

# field <file> <label-ERE> — the value of the first header field (above the first `## ` heading)
# whose label matches exactly; bullet/bold optional.
field() {
  awk -v lab="$2" '
    /^##[[:space:]]/ { exit }
    {
      line = $0
      sub(/^[[:space:]]*-[[:space:]]*/, "", line)
      if (match(line, "^\\*\\*(" lab "):\\*\\*[[:space:]]*") || match(line, "^(" lab "):[[:space:]]*")) {
        v = substr(line, RLENGTH + 1); sub(/[[:space:]]+$/, "", v)
        if (v != "") { print v; exit }
      }
    }' "$1" 2>/dev/null
}

# superseded <file> — an appended `Superseded by ADR-MMM …` line below the header, if any.
superseded() {
  awk '
    /^##[[:space:]]/ { body = 1 }
    body {
      line = $0
      sub(/^[[:space:]]*-[[:space:]]*/, "", line); gsub(/\*\*/, "", line)
      sub(/^Status:[[:space:]]*/, "", line)
      if (line ~ /^Superseded by ADR-[0-9]+/) { sub(/[[:space:]]+$/, "", line); v = line }
    }
    END { if (v != "") print v }' "$1" 2>/dev/null
}

cell() { printf '%s' "$1" | sed 's/|/\\|/g'; }

# Collect "NNN<TAB>filename" for numeric sort, then emit rows in that order.
tmp_rows="$(mktemp)" ; notes_tmp="$(mktemp)"
trap 'rm -f "$tmp_rows" "$notes_tmp" 2>/dev/null' EXIT

# Preserve any human-authored trailing section (from the first '## ' heading to EOF) so a
# generated index and hand-kept notes (e.g. a '## Notes' paragraph, Eleutheria's Appendix-F prose)
# can coexist and survive regeneration. The generated part below has no '## ' heading, so the
# first one in the existing file marks the boundary; regeneration normalises to one blank line
# before it. Read the existing README BEFORE the write truncates it.
if [ -f "$ADR_DIR/README.md" ]; then
  awk '/^##[[:space:]]/{f=1} f' "$ADR_DIR/README.md" > "$notes_tmp"
fi

for f in "$ADR_DIR"/ADR-*.md; do
  [ -f "$f" ] || continue
  base="$(basename "$f")"
  # NNN is the digits immediately after "ADR-".
  nnn="$(printf '%s\n' "$base" | sed -E 's/^ADR-0*([0-9]+).*$/\1/')"
  case "$nnn" in ''|*[!0-9]*) continue ;; esac   # skip non-numeric (e.g. README, _TEMPLATE)
  printf '%s\t%s\n' "$nnn" "$base" >> "$tmp_rows"
done

row_legacy() {   # the 0.4.0 rendering, byte for byte
  local f="$1" base="$2" title status ticket adr_id
  title="$(grep -m1 -E '^#[[:space:]]+ADR-[0-9]+:' "$f" | sed -E 's/^#[[:space:]]+ADR-[0-9]+:[[:space:]]*//; s/[[:space:]]*$//')"
  [ -n "$title" ] || title='—'
  status="$(legacy_field "$f" Status)"; [ -n "$status" ] || status='—'
  ticket="$(legacy_field "$f" Ticket)"; [ -n "$ticket" ] || ticket='—'
  adr_id="$(grep -m1 -E '^#[[:space:]]+ADR-[0-9]+:' "$f" | sed -E 's/^#[[:space:]]+(ADR-[0-9]+):.*$/\1/')"
  [ -n "$adr_id" ] || adr_id="$(printf '%s' "$base" | sed -E 's/^(ADR-[0-9]+).*$/\1/')"
  printf '| [%s](%s) | %s | %s | %s |\n' "$adr_id" "$base" "$title" "$ticket" "$status"
}

H1_RE='^#[[:space:]]+ADR-[0-9]+[[:space:]]*(:|—|-)'
row() {
  local f="$1" base="$2" title status ticket adr_id sup
  title="$(grep -m1 -E "$H1_RE" "$f" | sed -E 's/^#[[:space:]]+ADR-[0-9]+[[:space:]]*(:|—|-)[[:space:]]*//; s/[[:space:]]*$//')"
  [ -n "$title" ] || title='—'
  status="$(field "$f" 'Status')"
  sup="$(superseded "$f")"; [ -n "$sup" ] && status="$sup"
  [ -n "$status" ] || status='—'
  ticket="$(field "$f" 'Ticket')"
  [ -n "$ticket" ] || ticket="$(field "$f" 'Phase')"
  [ -n "$ticket" ] || ticket="$(field "$f" 'Phase / ticket')"
  [ -n "$ticket" ] || ticket='—'
  adr_id="$(grep -m1 -E "$H1_RE" "$f" | sed -E 's/^#[[:space:]]+(ADR-[0-9]+).*$/\1/')"
  [ -n "$adr_id" ] || adr_id="$(printf '%s' "$base" | sed -E 's/^(ADR-[0-9]+).*$/\1/')"
  printf '| [%s](%s) | %s | %s | %s |\n' "$adr_id" "$base" "$(cell "$title")" "$(cell "$ticket")" "$(cell "$status")"
}

emit() {
  printf '%s\n' "$MARKER"
  printf '# Architecture Decision Records\n\n'
  printf 'One row per ADR, numeric order. Regenerate with `build-memory adr-index`\n'
  printf '(`scripts/adr-index.sh`); never hand-edit — the validator diffs a regeneration.\n\n'
  printf '| ADR | Title | Ticket | Status |\n'
  printf '|---|---|---|---|\n'
  if [ -s "$tmp_rows" ]; then
    sort -n -k1,1 "$tmp_rows" | while IFS="$(printf '\t')" read -r _n base; do
      if [ "$LEGACY" -eq 1 ]; then row_legacy "$ADR_DIR/$base" "$base"; else row "$ADR_DIR/$base" "$base"; fi
    done
  fi
  # Re-append any preserved human trailing section (see the capture above).
  if [ -s "$notes_tmp" ]; then
    printf '\n'
    cat "$notes_tmp"
  fi
}

if [ "$CHECK" -eq 1 ]; then
  emit
else
  emit > "$ADR_DIR/README.md"
  echo "adr-index.sh: wrote $ADR_DIR/README.md"
fi
exit 0
